### ISSUE TITLE
Nothing happens when double clicked the desktop icon?

### ISSUE THREAD

**Issue by SuhanKoh** [headmelted/code-builds#7]
I installed the package on my Raspberry Pi3 running raspbian. With this package, code-oss_1.8.0-2016112710_armhf.deb, does it matter if I run it with VNC?

**Comment by SuhanKoh** [comment]
Nevermind, I found a fix for this. Just have to use built in rasbian VNC with the VNCViewer. TightVNC block code-oss from being boot up.

**Comment by olijf** [comment]
I think I found a fix with this.. try running code-oss --disable-gpu 
In my virtualbox this solved everything.

**Comment by headmelted** [comment]
Glad you were able to get this working. I know there are a lot of folks
remoting onto their Pi's, so this is really helpful for the next person
that comes along!

On 6 Dec 2016 21:35, "Olaf van der Kruk" <notifications@github.com> wrote:

I think I found a fix with this.. try running code-oss --disable-gpu
In my virtualbox this solved everything.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/headmelted/code-builds/issues/7#issuecomment-265279888>,
or mute the thread

**Comment by SuhanKoh** [comment]
I actually found this link, and I switched the VNC then it worked, https://github.com/Microsoft/vscode/issues/9016 just FYI.

**Comment by headmelted** [comment]
Thanks for posting this tip. Variants of this issue have been mentioned to
me a couples of times before, so its great to have somewhere to point
people for a solution.

Glad you got this resolved!! :-)
